local QBCore = exports['qb-core']:GetCoreObject()

--all 4th side of vehicles | registring evenets
RegisterServerEvent("psychic-system:add_rear")
AddEventHandler("psychic-system:add_rear", function(vehicle, players)
	TriggerClientEvent("psychic-system:add_rear", -1, vehicle, players)
end)
RegisterServerEvent("psychic-system:add_front")
AddEventHandler("psychic-system:add_front", function(vehicle, players)
	TriggerClientEvent("psychic-system:add_front", -1, vehicle, players)
end)
RegisterServerEvent("psychic-system:rem_rear")
AddEventHandler("psychic-system:rem_rear", function(vehicle)
	TriggerClientEvent("psychic-system:rem_rear", -1, vehicle)
end)
RegisterServerEvent("psychic-system:rem_front")
AddEventHandler("psychic-system:rem_front", function(vehicle)
	TriggerClientEvent("psychic-system:rem_front", -1, vehicle)
end)
